//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using BizStream.Extensions.Kentico.Xperience.Caching.Tests.Models;
using CMS;
using CMS.Base;
using CMS.CustomTables;
using CMS.DataEngine;
using CMS.Helpers;

[assembly: RegisterCustomTable( TestItem.CLASS_NAME, typeof( TestItem ) )]

namespace BizStream.Extensions.Kentico.Xperience.Caching.Tests.Models
{
    /// <summary>
    /// Represents a content item of type TestItem.
    /// </summary>
    public partial class TestItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BizStream.Test";


        /// <summary>
        /// The instance of the class that provides extended API for working with TestItem fields.
        /// </summary>
        private readonly TestItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Value.
        /// </summary>
        [DatabaseField]
        public string Value
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Value" ), @"" );
            }
            set
            {
                SetValue( "Value", value );
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with TestItem fields.
        /// </summary>
        [RegisterProperty]
        public TestItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with TestItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class TestItemFields : AbstractHierarchicalObject<TestItemFields>
        {
            /// <summary>
            /// The content item of type TestItem that is a target of the extended API.
            /// </summary>
            private readonly TestItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="TestItemFields" /> class with the specified content item of type TestItem.
            /// </summary>
            /// <param name="instance">The content item of type TestItem that is a target of the extended API.</param>
            public TestItemFields( TestItem instance )
            {
                mInstance = instance;
            }


            /// <summary>
            /// Value.
            /// </summary>
            public string Value
            {
                get
                {
                    return mInstance.Value;
                }
                set
                {
                    mInstance.Value = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="TestItem" /> class.
        /// </summary>
        public TestItem( ) : base( CLASS_NAME )
        {
            mFields = new TestItemFields( this );
        }

        #endregion
    }
}
